# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title: Marcin Grabski
email: marcin at grabski dot me
description: >- # this means to ignore newlines until "baseurl:"
   Another human being. Life is an experiment.
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://www.grabski.me" # the base hostname & protocol for your site, e.g. http://example.com

# Build settings
markdown: kramdown
theme: minima
plugins:
  - jekyll-feed
collections:
  photos:
     output: true
     permalink: /:collection/:title/

# general permalink for posts
# Rather than typing permalink: /:categories/:year/:month/:day/:title/
# you can just type permalink: pretty
permalink: /posts/:year/:month/:title/

defaults:
  - scope:
      path: ""
      type: "photos"
      permalink: /photos/:title/
    values:
      layout: "photo_set"
      photos_license: https://creativecommons.org/licenses/by/4.0/


compress_html:
  clippings: all
  comments:  all
  endings:   all
      

keep_files:
#   - node_modules/lightgallery.js/

header_pages:
  - posts_index.md
  - photos_index.md
  - about.md

# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
exclude:
   - .sass-cache/
   - .jekyll-cache/
   - gemfiles/
   - Gemfile
   - Gemfile.lock
   - node_modules/
   - vendor/bundle/
   - vendor/cache/
   - vendor/gems/
   - vendor/ruby/    
   - photosets.yml
   - '*.code-workspace'
   - README.md
   

